---
# Minimum bounty which could be set on a player
min_bounty: 10000
# Bounty Fine on victim Death. 1 = Enabled
bounty_fine: 1
# Percentage of the bounty on the player to reduce as Bounty Fine
fine_percentage: 10
...

